#pragma once
#include "CoreMinimal.h"
#include "EControllerVibrationType.generated.h"

UENUM(BlueprintType)
enum class EControllerVibrationType : uint8 {
    Afterburner,
    AirBrake,
    Buffet,
    Stall,
    HighGTurn,
    GunFire,
    MissileSmallFire,
    MissileLargeFire,
    BombFire,
    RocketFire,
    RailgunFire,
    LaserFire,
    FlareFire,
    TakeOffBase,
    TakeOffCarrier,
    LandingBase,
    LandingCarrier,
    AerialRefuel,
    GunDamage,
    MissileDamage,
    PlaneCrashed,
    OwnPlaneDestroyed,
    CameraPlaneExplosion,
    EnteredClouds,
    InCloudsA,
    InCloudsB,
    Icing,
    AirCurrent,
    IGCTakeOff,
    IGCEquipped,
    ExitCloudCameraShake,
    BombImpact,
    SmallBombImpact,
    Explosion,
    GeneralPurposeS,
    GeneralPurposeM,
    GeneralPurposeL,
    HeliosDamage,
    EnemyExplosion,
    InAirCurrentCameraShake,
    Lightning,
    EMLBulletDamage,
    RectennaBarrierDamage,
    HeliosBombImpact,
    HeliosBombImpactLoop,
    SubmarineSearch,
    None,
};

