#pragma once
#include "CoreMinimal.h"
#include "EMedalTitle.generated.h"

UENUM(BlueprintType)
enum class EMedalTitle : uint8 {
    Ace,
    MachineGunCrazy,
    SteamRoller,
    FirstIn,
    LastOut,
    Adaptable,
    BBQ,
    IronMan,
    Efficient,
    HaloPilot,
    GroundProximityWarning,
    Speedster,
    Tortoise,
    DangerousDriving,
    AeroMaster,
    SoloWing,
    BailoutMaster,
    Specter,
    TriggerHappy,
    GunMaster,
    Fireworks,
    Pacifist,
    SharpShooter,
    ShotgunStyle,
    BountyHunter,
    RollingThunder,
    CoolHead,
    Survivor,
    MechanicsFriend,
    AlanSmithee,
    GimmeAmmo,
    AGiftFromDeath,
    Entourage,
    Independent,
    CloudSeeker,
    Nephophobic,
    HideAndSeeker,
    FinalWord,
    EscapeArtist,
    StarBlade,
    Excalibur,
    Bullfighter,
    Num,
};

