#pragma once
#include "CoreMinimal.h"
#include "EUIBgms.generated.h"

UENUM(BlueprintType)
enum class EUIBgms : uint8 {
    None,
    MainTitle,
    MainMenu,
    MainMenuCampaign,
    Briefing1,
    Briefing2,
    Briefing3,
    Briefing4,
    Briefing4_2,
    Briefing4_3,
    Briefing5,
    BriefingMS05,
    BriefingMS16,
    Debriefing1,
    Debriefing2,
    Debriefing3,
    Debriefing4,
    Debriefing5,
    Hangar1,
    Hangar2,
    Hangar3,
    Hangar4,
    Hangar5,
    HangarMS16,
    Hangar3_2,
    StaffCredits,
    VRTitle,
    VRMenu,
    VRBriefing,
    VRDebriefing,
    VRHangar,
    VRPrologue,
    VREnding,
    VRGameOver,
    MultiMenu,
    MultiLobby,
    MultiHangar,
    MultiReady,
    MultiEndLoseJingle,
    MultiEndWinJingle,
    MultiEndMVPJingle,
    BriefingEx1,
    BriefingEx2,
    BriefingEx3,
    DebriefingEx1,
    DebriefingEx2,
    DebriefingEx3,
    HangarEx1,
    HangarEx2,
    HangarEx3,
    MultiCollaborationJingle,
    Num,
};

