#pragma once
#include "CoreMinimal.h"
#include "EWeaponID.generated.h"

UENUM(BlueprintType)
enum class EWeaponID : uint8 {
    WID_mg,
    WID_msl,
    WID_4aam,
    WID_4agm,
    WID_6aam,
    WID_8aam,
    WID_8agm,
    WID_eml,
    WID_gpb,
    WID_grkt,
    WID_hcaa,
    WID_hpaa,
    WID_hvaa,
    WID_laam,
    WID_lacm,
    WID_lagm,
    WID_lasm,
    WID_mgp,
    WID_qaam,
    WID_rkt,
    WID_saam,
    WID_sasm,
    WID_plsl,
    WID_sffs,
    WID_sod,
    WID_tls,
    WID_uav,
    WID_ugb,
    WID_xsdb,
    WID_faeb,
    WID_mpbm,
    WID_ecm,
    WID_pgun,
    WID_mstm,
    WID_admm,
    WID_tgtp = 0x64,
    WID_uav_plsl,
    WID_sod_child,
    WID_sffs_child,
    WID_droptank,
    WID_AI_gun = 0x96,
    WID_AI_gun_emitter,
    WID_AI_aagun,
    WID_AI_aam,
    WID_AI_longrange_aam,
    WID_AI_artillery,
    WID_AI_bomb,
    WID_AI_ciws,
    WID_AI_laser_interceptor,
    WID_AI_rktl,
    WID_AI_sam,
    WID_AI_vls,
    WID_AI_aias_aam,
    WID_AI_aias_lcn,
    WID_AI_aias_plc,
    WID_AI_aias_htb,
    WID_AI_eml,
    WID_AI_eml_stonehenge,
    WID_AI_lpg,
    WID_AI_mop,
    WID_AI_rbr,
    WID_AI_utl,
    WID_AI_ssm,
    WID_AI_ecm,
    WID_NONE = 0xFE,
    WID_MAX UMETA(Hidden),
};

