#pragma once
#include "CoreMinimal.h"
#include "SoundChannelType.generated.h"

UENUM(BlueprintType)
enum class SoundChannelType : uint8 {
    Explosion,
    ExplosionMissileTarget,
    ExplosionMissileGround,
    ExplosionMissileSea,
    ExplosionMissileAir,
    ExplosionBombGround,
    ExplosionBombSea,
    ExplosionTargetSmallGround,
    ExplosionAlicornInternal,
    ExplosionFAEB,
    ExplosionMPBM,
    ExplosionAirTarget,
    ExplosionGroundTarget,
    ExplosionAirTargetLarge,
    ExplosionGroundTargetLarge,
    ExplosionPlayerCrash,
    ExplosionOtherPlaneCrash,
    ExplosionOtherPlanePartsFalling,
    ExplosionOtherPlanePartsFallingStop,
    ExplosionOtherPlanePartsFallingFinal,
    ExplosionOtherPlanePartsSecondary,
    ExplosionAA,
    LandingGearDown,
    LandingGearUp,
    LandingGearSkid,
    PlayerTakeoff,
    PlayerRefuelingDocking,
    GunHit,
    BuildingHit,
    BuildingDown,
    ExplosionHelios,
    ExplosionSupplyPlane,
    BunkerBusterDrop,
    BunkerBusterHit,
    BunkerBusterMiss,
    PlatformJunctionDestruction,
    PlatformSplash,
    BridgeSplash,
    ShipCrushedByPlatform,
    OilTankDestruction,
    PlayerPostStallManeuver,
    BulletPassSound,
    RectennaBarrierHit,
    DroneRectennaBarrierHit,
    IRBMExplosion,
    UAVSuicide,
    MGPHit,
    EMLHit,
    TLSHit,
    PLSLHit,
    FasFire,
    FasFireStop,
    FasBank,
    FasFall,
    FasDown,
    FasDestruction,
    FasPropellerDestruction,
    SFFSSplit,
    ChannelCount,
    None,
};

